use_frameworks!

target 'VEDAuth_Example' do
    pod 'VEDAuth', :path => '../'

  target 'VEDAuth_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
